name: Daily Football Predictions

on:
  schedule:
    # Ώρες Ελλάδας (EEST): 08:00, 12:00, 16:00, 20:00
    # Μετατροπή σε UTC (3 ώρες πίσω): 05:00, 09:00, 13:00, 17:00
    - cron: '0 5,9,13,17 * * *'
  workflow_dispatch: # Σου επιτρέπει να το τρέχεις και χειροκίνητα όποτε θες εσύ

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Δίνει δικαίωμα στο ρομποτάκι να γράφει και να ανανεώνει το daily_predictions.txt

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run prediction model
        run: python main.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add daily_predictions.txt history.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update predictions & statistics"
          git push
