name: Daily Football Predictions

on:
  schedule:
    # Τρέχει αυτόματα 4 φορές τη μέρα (Ώρες Ελλάδας: 09:00, 13:00, 17:00, 21:00)
    - cron: '0 6,10,14,18 * * *'
  workflow_dispatch: # Σου επιτρέπει να το τρέχεις και χειροκίνητα όποτε θες εσύ

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run prediction model
        run: python main.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add daily_predictions.txt
          git commit -m "Αυτόματη ανανέωση σημερινών προγνωστικών" || exit 0
          git push

